title: Nosheen Altaf # your name (or website title) here
logo: "/images/ProfilePic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist
  <br><br>
  10+ Years of professional experience in various industries including Retail, Automotive, Higher Education, Customer Analytics and Market Research etc. 
  <br><br>
  <br><br>
  <a href="https://www.linkedin.com/in/nosheen-altaf-565158a/">View My LinkedIn Profile</a> 
  <br><br>
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
